---
- name: Update apt-cache
  ansible.builtin.apt:
    # name: "*"
    # state: latest
    update_cache: true

- name: Ensure sudo is installed
  become: true
  ansible.builtin.apt:
    name: sudo
    state: present
